# Generated by Django 4.0.1 on 2022-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Aadhar', models.IntegerField(default='')),
                ('Department', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
